server:
  port: 8081
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: path_route
          uri: http://localhost:7001/ #lb://clienthi
#           http://20.20.56.114:8080/
          predicates:
            - Path=/abc/**
          filters:
                - StripPrefix=1           # 去除原请求地址中的abc

        - id: path_route1
          uri: lb://CLIENTHI
          #           http://20.20.56.114:8080/
          predicates:
            - Path=/bcd/**
          filters:
            - StripPrefix=1           # 去除原请求地址中的abc
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:7000/eureka/