server:
  port: 8081
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: path_route
          uri: lb://clienthi #http://127.0.0.1:7002
#           http://20.20.56.114:8080/
          predicates:
            - Path=/meteor_93/**
          filters:
                - StripPrefix=1           # 去除原请求地址中的meteor_93
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:7000/eureka/